on:
  workflow_call:
    inputs:
      GITPULLER_HOST:
        required: true
        type: string
    secrets:
      GITPULLER_KEY:
        required: false
        type: string
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      id: PullRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: '${{ inputs.GITPULLER_HOST }}/gitpuller.php'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"repo": "${{ github.repository }}", "GITPULLER_KEY": "${{ secrets.GITPULLER_KEY }}"}'
    - name: Response
      run: |
        echo ${{ steps.PullRequest.outputs.response }}
        echo ${{ steps.PullRequest.outputs.headers }}
        echo ${{ fromJson(steps.PullRequest.outputs.response).result }}
